/*
@license
dhtmlxScheduler v.5.1.0 Stardard

This software is covered by GPL license. You also can obtain Commercial or Enterprise license to use it in non-GPL project - please contact sales@dhtmlx.com. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
scheduler.date.add_agenda=function(e){return scheduler.date.add(e,1,"year")},scheduler.templates.agenda_time=function(e,t,a){return a._timed?this.day_date(a.start_date,a.end_date,a)+" "+this.event_date(e):scheduler.templates.day_date(e)+" &ndash; "+scheduler.templates.day_date(t)},scheduler.templates.agenda_text=function(e,t,a){return a.text},scheduler.templates.agenda_date=function(){return""},scheduler.date.agenda_start=function(){return scheduler.date.date_part(scheduler._currentDate())},scheduler.attachEvent("onTemplatesReady",function(){
function e(e){if(e){var t=scheduler.locale.labels,a=scheduler._waiAria.agendaHeadAttrString(),r=scheduler._waiAria.agendaHeadDateString(t.date),i=scheduler._waiAria.agendaHeadDescriptionString(t.description);scheduler._els.dhx_cal_header[0].innerHTML="<div "+a+" class='dhx_agenda_line'><div "+r+">"+t.date+"</div><span style='padding-left:25px' "+i+">"+t.description+"</span></div>",scheduler._table_view=!0,scheduler.set_sizes()}}function t(){var e=(scheduler._date,scheduler.get_visible_events());e.sort(function(e,t){
return e.start_date>t.start_date?1:-1});for(var t,a=scheduler._waiAria.agendaDataAttrString(),r="<div class='dhx_agenda_area' "+a+">",i=0;i<e.length;i++){var n=e[i],s=n.color?"background:"+n.color+";":"",o=n.textColor?"color:"+n.textColor+";":"",d=scheduler.templates.event_class(n.start_date,n.end_date,n);t=scheduler._waiAria.agendaEventAttrString(n);var l=scheduler._waiAria.agendaDetailsBtnString();r+="<div "+t+" class='dhx_agenda_line"+(d?" "+d:"")+"' event_id='"+n.id+"' style='"+o+s+(n._text_style||"")+"'><div class='dhx_agenda_event_time'>"+scheduler.templates.agenda_time(n.start_date,n.end_date,n)+"</div>",
r+="<div "+l+" class='dhx_event_icon icon_details'>&nbsp;</div>",r+="<span>"+scheduler.templates.agenda_text(n.start_date,n.end_date,n)+"</span></div>"}r+="<div class='dhx_v_border'></div></div>",scheduler._els.dhx_cal_data[0].innerHTML=r,scheduler._els.dhx_cal_data[0].childNodes[0].scrollTop=scheduler._agendaScrollTop||0;var _=scheduler._els.dhx_cal_data[0].childNodes[0],c=_.childNodes[_.childNodes.length-1];c.style.height=_.offsetHeight<scheduler._els.dhx_cal_data[0].offsetHeight?"100%":_.offsetHeight+"px";
var h=scheduler._els.dhx_cal_data[0].firstChild.childNodes;scheduler._els.dhx_cal_date[0].innerHTML=scheduler.templates.agenda_date(scheduler._min_date,scheduler._max_date,scheduler._mode),scheduler._rendered=[];for(var i=0;i<h.length-1;i++)scheduler._rendered[i]=h[i]}var a=scheduler.dblclick_dhx_cal_data;scheduler.dblclick_dhx_cal_data=function(){if("agenda"==this._mode)!this.config.readonly&&this.config.dblclick_create&&this.addEventNow();else if(a)return a.apply(this,arguments)},scheduler.attachEvent("onSchedulerResize",function(){
return"agenda"==this._mode?(this.agenda_view(!0),!1):!0});var r=scheduler.render_data;scheduler.render_data=function(e){return"agenda"!=this._mode?r.apply(this,arguments):void t()};var i=scheduler.render_view_data;scheduler.render_view_data=function(){return"agenda"==this._mode&&(scheduler._agendaScrollTop=scheduler._els.dhx_cal_data[0].childNodes[0].scrollTop,scheduler._els.dhx_cal_data[0].childNodes[0].scrollTop=0),i.apply(this,arguments)},scheduler.agenda_view=function(a){scheduler._min_date=scheduler.config.agenda_start||scheduler.date.agenda_start(scheduler._date),
scheduler._max_date=scheduler.config.agenda_end||scheduler.date.add_agenda(scheduler._min_date,1),e(a),a?(scheduler._cols=null,scheduler._colsS=null,scheduler._table_view=!0,t()):scheduler._table_view=!1}});
//# sourceMappingURL=../sources/ext/dhtmlxscheduler_agenda_view.js.map