/*
dhtmlxScheduler v.4.3.0 Stardard

This software is covered by GPL license. You also can obtain Commercial or Enterprise license to use it in non-GPL project - please contact sales@dhtmlx.com. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
!function(){scheduler.config.container_autoresize=!0,scheduler.config.month_day_min_height=90;var e=scheduler._pre_render_events,t=!0;scheduler._pre_render_events=function(s,i){if(!scheduler.config.container_autoresize||!t)return e.apply(this,arguments);var a=this.xy.bar_height,n=this._colsS.heights,r=this._colsS.heights=[0,0,0,0,0,0,0],d=this._els.dhx_cal_data[0];if(s=this._table_view?this._pre_render_events_table(s,i):this._pre_render_events_line(s,i),this._table_view)if(i)this._colsS.heights=n;
else{var l=d.firstChild;if(l.rows){for(var o=0;o<l.rows.length;o++){if(r[o]++,r[o]*a>this._colsS.height-this.xy.month_head_height){var h=l.rows[o].cells,_=this._colsS.height-this.xy.month_head_height;1*this.config.max_month_events!==this.config.max_month_events||r[o]<=this.config.max_month_events?_=r[o]*a:(this.config.max_month_events+1)*a>this._colsS.height-this.xy.month_head_height&&(_=(this.config.max_month_events+1)*a);for(var c=0;c<h.length;c++)h[c].childNodes[1].style.height=_+"px";r[o]=(r[o-1]||0)+h[0].offsetHeight
}r[o]=(r[o-1]||0)+l.rows[o].cells[0].offsetHeight}r.unshift(0),l.parentNode.offsetHeight<l.parentNode.scrollHeight&&!l._h_fix}else if(s.length||"visible"!=this._els.dhx_multi_day[0].style.visibility||(r[0]=-1),s.length||-1==r[0]){var u=(l.parentNode.childNodes,(r[0]+1)*a+1+"px");d.style.top=this._els.dhx_cal_navline[0].offsetHeight+this._els.dhx_cal_header[0].offsetHeight+parseInt(u,10)+"px",d.style.height=this._obj.offsetHeight-parseInt(d.style.top,10)-(this.xy.margin_top||0)+"px";var g=this._els.dhx_multi_day[0];
g.style.height=u,g.style.visibility=-1==r[0]?"hidden":"visible",g=this._els.dhx_multi_day[1],g.style.height=u,g.style.visibility=-1==r[0]?"hidden":"visible",g.className=r[0]?"dhx_multi_day_icon":"dhx_multi_day_icon_small",this._dy_shift=(r[0]+1)*a,r[0]=0}}return s};var s=["dhx_cal_navline","dhx_cal_header","dhx_multi_day","dhx_cal_data"],i=function(e){for(var t=0,i=0;i<s.length;i++){var a=s[i],n=scheduler._els[a]?scheduler._els[a][0]:null,r=0;switch(a){case"dhx_cal_navline":case"dhx_cal_header":r=parseInt(n.style.height,10);
break;case"dhx_multi_day":r=n?n.offsetHeight:0,1==r&&(r=0);break;case"dhx_cal_data":r=Math.max(n.offsetHeight-1,n.scrollHeight);var d=scheduler.getState().mode;if("month"==d){if(scheduler.config.month_day_min_height&&!e){var l=n.getElementsByTagName("tr").length;r=l*scheduler.config.month_day_min_height}e&&(n.style.height=r+"px")}if(scheduler.matrix&&scheduler.matrix[d])if(e)r+=2,n.style.height=r+"px";else{r=2;for(var o=scheduler.matrix[d],h=o.y_unit,_=0;_<h.length;_++)r+=h[_].children?o.folder_dy||o.dy:o.dy
}("day"==d||"week"==d)&&(r+=2)}t+=r}scheduler._obj.style.height=t+"px",e||scheduler.updateView()},a=function(){if(!scheduler.config.container_autoresize||!t)return!0;var e=scheduler.getState().mode;i(),(scheduler.matrix&&scheduler.matrix[e]||"month"==e)&&window.setTimeout(function(){i(!0)},1)};scheduler.attachEvent("onViewChange",a),scheduler.attachEvent("onXLE",a),scheduler.attachEvent("onEventChanged",a),scheduler.attachEvent("onEventCreated",a),scheduler.attachEvent("onEventAdded",a),scheduler.attachEvent("onEventDeleted",a),scheduler.attachEvent("onAfterSchedulerResize",a),scheduler.attachEvent("onClearAll",a),scheduler.attachEvent("onBeforeExpand",function(){return t=!1,!0
}),scheduler.attachEvent("onBeforeCollapse",function(){return t=!0,!0})}();
//# sourceMappingURL=../sources/ext/dhtmlxscheduler_container_autoresize.js.map